env:
  es2021: true
  node: true

extends: standard-with-typescript
overrides: []

parserOptions:
  ecmaVersion: latest
  sourceType: module
  project:
    - tsconfig.json
    - tsconfig.tests.json

rules:
  "@typescript-eslint/explicit-function-return-type":
    - off
  "@typescript-eslint/quotes":
    - error
    - double
  "@typescript-eslint/semi":
    - error
    - always